# Generated by Django 2.0.7 on 2018-10-05 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflowlevel2_uuid', models.CharField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique ID to relate back to Bifrost workflow', max_length=255, unique=True, verbose_name='WorkflowLevel2 UUID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('make', models.CharField(blank=True, help_text='Who made the product', max_length=255, null=True)),
                ('model', models.CharField(blank=True, help_text='What is the model from the manufacturer', max_length=255, null=True)),
                ('style', models.CharField(blank=True, help_text='Distinguishing look or color of product', max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text='Detailed info', max_length=255, null=True)),
                ('type', models.CharField(blank=True, help_text='Type of product', max_length=255, null=True)),
                ('status', models.CharField(blank=True, help_text='Status of Product (in-stock, on back order etc.) ', max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='Unique ID for external tracking or thrid part data system', max_length=255, null=True, verbose_name='Product identifier')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dynamic Field name for additional meta definition of a product', max_length=255)),
                ('type', models.CharField(blank=True, help_text='Type of field', max_length=255, null=True)),
                ('value', models.CharField(help_text='Dynamic Field value for additional meta definition of a product', max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
