# Generated by Django 2.0.7 on 2019-01-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181218_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='workflowlevel2_uuid',
            field=models.CharField(blank=True, help_text='Unique ID to relate back to Bifrost workflow', max_length=255, verbose_name='WorkflowLevel2 UUID'),
        ),
    ]
