# Generated by Django 2.0.7 on 2019-02-14 09:28

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=products.models.make_filepath),
        ),
        migrations.AddField(
            model_name='product',
            name='file_name',
            field=models.CharField(blank=True, help_text='Filename', max_length=50, null=True),
        ),
    ]
